### ISSUE TITLE
Maxence's old and buggy bet system need to be replaced with my superior coding

### ISSUE THREAD

**Issue by Alb5000-Dev** [jb-jambon-beurre/pok3r#1]

**Comment by Max1Truc** [comment]
What did you do ? Nothing. I mean: did you work on the bet system ? Nope.

**Comment by Alb5000-Dev** [comment]
WhAt DiD yOu Do ? Oh, just did the entire check system while you were slacking off, but nothing important.

(For future reference, this is a fake discussion)
